import {images} from '../../constants';

const {project1,project2,project3,project4,project5,project6}=images;
export const Project = [
    { id: 1, 
        projectType: "js",
       image : project1,
       title: "BLOG WEBSITE",
       subTitle: "PROTOTYPE",
       gitHubLink : "https://github.com/Krish1rst/codealpha_BlogWebsite",
       liveLink :"https://krish1rst.github.io/codealpha_BlogWebsite/",
     },
     { id: 2, 
        projectType: "js",
        image : project2,
        title: "PORTFOLIO WEBSITE",
        subTitle: "PORTFOLIO PROTOTYPE",
        gitHubLink : "https://github.com/Krish1rst/Portfolio",
        liveLink :"https://krish1rst.github.io/Portfolio/",
      },
      { id: 3, 
        projectType: "js",
        image : "https://images.alphacoders.com/102/thumbbig-10203.webp",
        title: "CHESS",
        subTitle: "GAME",
        gitHubLink : "https://github.com/Krish1rst/Chess_Game",
        liveLink :"https://chessified.netlify.app/",
      },
      { id: 4, 
        projectType: "react",
       image : project4,
       title: "TEXTUTILS",
       subTitle: "TEXT MANIPULATION PROJECT ",
       gitHubLink : "https://github.com/Krish1rst/TextUtils_Krishna",
       liveLink :"https://spectacular-youtiao-b8c139.netlify.app/",
     },
     { id: 5, 
        projectType: "react",
        image : project5,
        title: "NewsDaily",
        subTitle: "NEWS API PROJECT",
        gitHubLink : "https://github.com/Krish1rst/NewsDaily",
        liveLink :"",
      },
      { id: 6, 
        projectType: "react",
        image : project6,
        title: "PORTFOLIO",
        subTitle: "MY PERSONAL PORTFOLIO",
        gitHubLink : "https://github.com/Krish1rst/ReactPortfolio",
        liveLink :"#",
      },
    
  ];


